server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # reservations (elements-service)
            - id: elements
              uri: http://localhost:8082
              predicates:
                - Path=/api/reservations/**
            # internal sync (elements-service)
            - id: elements-internal-sync
              uri: http://localhost:8082
              predicates:
                - Path=/internal-sync/categories/**
            # services/clients/employees/rooms (category-service)
            - id: category
              uri: http://localhost:8081
              predicates:
                - Path=/api/services/**,/api/clients/**,/api/employees/**,/api/rooms/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
