server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: category
          uri: http://localhost:8081
          predicates:
            - Path=/api/clients/**,/api/employees/**,/api/services/**,/api/rooms/**
        - id: elements
          uri: http://localhost:8082
          predicates:
            - Path=/api/reservations/**,/api/payments/**,/api/reservations/*/payment
      default-filters:
        - RemoveHopByHop=connection,keep-alive,proxy-authenticate,proxy-authorization,te,trailers,transfer-encoding,upgrade

management:
  endpoints:
    web:
      exposure:
        include: health
